BASE_TASK_CONFIG_PATH: habitat_extensions/config/map_cma/gt_semantics/iterative_task.yaml
NUM_ENVIRONMENTS: 4
TENSORBOARD_DIR: data/tensorboard_dirs/map_cma/gt_semantics/episodic_maps/1_ftune/episodic_evals
EVAL_CKPT_PATH_DIR: data/checkpoints/map_cma/gt_semantics/episodic_maps/1_ftune
LOG_FILE: data/logs/map_cma/gt_semantics/episodic_maps/1_ftune
RESULTS_DIR: data/checkpoints/map_cma/gt_semantics/episodic_maps/1_ftune/episodic_evals

EVAL:
  SPLIT: val_unseen
  iterative_map_reset: episodic

RL:
  POLICY:
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: [GTSemanticsIterativeMapper]

MODEL:
  policy_name: MapCMAPolicy
